#include "asm.h"
#include "memlayout.h"
#include "mmu.h"
#include "boot_macros.S"

# Start the first CPU: switch to 32-bit protected mode, jump into C.
# The BIOS loads this code from the first sector of the hard disk into
# memory at physical address 0x7c00 and starts executing in real mode
# with %cs=0 %ip=7c00.

.code16                       # Assemble for 16-bit mode
.globl start
start:
  CLI_AND_ZERO_DS_ES_SS

  # Physical address line A20 is tied to zero so that the first PCs 
  # with 2 MB would run software that assumed 1 MB.  Undo that.
seta20.1:
  inb     $0x64,%al               # Wait for not busy
  testb   $0x2,%al
  jnz     seta20.1

  movb    $0xd1,%al               # 0xd1 -> port 0x64
  outb    %al,$0x64

seta20.2:
  inb     $0x64,%al               # Wait for not busy
  testb   $0x2,%al
  jnz     seta20.2

  movb    $0xdf,%al               # 0xdf -> port 0x60
  outb    %al,$0x60

  SWITCH_TO_PROTECTED_MODE_AND_JUMP

.code32  # Tell assembler to generate 32-bit code now.
start32:
  SETUP_PROTECTED_MODE_DATA_SEGMENT_REGISTERS

  # Set up the stack pointer and call into C.
  movl    $start, %esp
  call    bootmain

  # If bootmain returns (it shouldn't), trigger a Bochs
  # breakpoint if running under Bochs, then halt.
  TRIGGER_BOCHS_BREAKPOINT_AND_HALT

BOOTSTRAP_GDT

